### ISSUE TITLE
Support for helm3 with no tiller

### ISSUE THREAD

**Issue by PhillipDowney** [IBM/Db2#10]
how do you configure db2u with Helm 3 when tiller does not exist ?

**Comment by Doout** [comment]
The next release should have it supported, is there a reason you need to use helm 3? It is possible to deploy on helm 3, but it just requires some change to the deploy script and one edit to the chart.

**Comment by joscorga** [comment]
Hi, I'm looking into installing DB2 on OpenShift v3.11.157 running on PPC as mentioned in the issue #7276, from the last comment I understand it is possible to install db2u using helm 3 making some changes, would it be possible to update the documentation provided here https://github.com/IBM/Db2/tree/develop/deployment with the steps required?

Thanks

**Comment by Doout** [comment]
@joscorga Power support for db2 on openshift will be coming later this year.

**Comment by PhillipDowney** [comment]
I installed 2.16 and got it to work, but for someone getting started with open source Kubernetes  you typically go for the latest , and of course this did not work because tiller was not there. Have got db2u up and running on Minikube now

**Comment by joscorga** [comment]
Thanks for your response @Doout, just to confirm are you saying today it is not possible to have DB2 on OpenShift running on Power? We have a project where we're looking into having OpenShift on Power and the application uses DB2 so if there is no way today to have DB2 we'd need to consider using an alternative as MariaDB.
