### ISSUE TITLE
Installation failure due to incompatible versions

### ISSUE THREAD

**Issue by chainhead** [IBM/Db2#11]
After accepting the license, the installation fails with this error message:

```bash
Error: incompatible versions client[v2.16.1] server[v2.14.3]
```
Can you please advise?

**Comment by abikbaghdasarian1** [comment]
The helm binary (client) is incompatible with the tiller (server) version in your cluster.

You can download the v2.14.3 binary from [here](https://github.com/helm/helm/releases/tag/v2.14.3).

**Comment by chainhead** [comment]
Yes, I was able to resolve this issue after updating `helm init --update`.
