### ISSUE TITLE
release v11.5.1.0 images have disappeared?

### ISSUE THREAD

**Issue by xfabre** [IBM/Db2#13]
It seems it's no more possible to pull 11.5.1.0 images.
```bash
> docker pull ibmcom/db2:11.5.1.0
Error response from daemon: manifest for ibmcom/db2:11.5.1.0 not found: manifest unknown: manifest unknown
```
while
```bash
> docker pull ibmcom/db2:11.5.1.0-CN1
11.5.1.0-CN1: Pulling from ibmcom/db2
37b1dccd0828: Already exists 
70cf862fdf8a: Already exists 
<...>
```
works as expected.
Strange enough, the image seems to be here in the registry
```
> docker-ls tags ibmcom/db2
requesting list . done
repository: ibmcom/db2
tags:
- 11.5.0.0
- 11.5.0.0a
- 11.5.1.0
- 11.5.1.0-CN1
- latest
```
Thus it's no more possible to install v11.5.1.0 release and as the image pull policy is set by default to `Always`, it means that in an already installed release, a pod will fail to restart even if the image is already here in the node's docker registry.

**Comment by irinadel** [comment]
@xfabre `11.5.1.0-CN1` should be used instead. `11.5.1.0` was pulled out.
