### ISSUE TITLE
Unable to apply db2 license

### ISSUE THREAD

**Issue by xfabre** [IBM/Db2#14]
with version 11.5.1.0-CN1, the `<release-name>-db2u-0` pod never reaches a ready state.
In the pod logs, I see:
```
[17987911.557092] db2u_root_entrypoint.sh[20]: + sudo /opt/ibm/db2/V11.5.0.0/adm/db2licm -a /db2u/license/db2u-lic
[17987911.646054] db2u_root_entrypoint.sh[20]: LIC1416N  The license could not be added automatically.  Return code: "-100".
[17987911.649329] db2u_root_entrypoint.sh[20]: + [[ 156 -ne 0 ]]
[17987911.649459] db2u_root_entrypoint.sh[20]: + echo '(*) Unable to apply db2 license.'
[17987911.649556] db2u_root_entrypoint.sh[20]: (*) Unable to apply db2 license.
[17987911.649648] db2u_root_entrypoint.sh[20]: + exit 1
```
I've accepted the license when I've run
```bash
./db2u-install --db-type db2oltp --namespace test-db2 --release-name testdb2 --tiller-namespace tiller --storage-class managed-nfs-storage
```
and the license is here in a configuration map with sensible dates
```bash
> kubectl get cm testdb2-db2u-lic -o yaml
apiVersion: v1
data:
  db2u-lic: |
    [LicenseCertificate]
    CheckSum=07DFC9F9DC7216727C19F837243E1B6E
<..>
    ProductName=IBM DB2 Developer-C Edition
    ProductID=1432
    ProductVersion=11.5
<...>
    LicenseStartDate=05/09/2019
    LicenseDuration=6812
    LicenseEndDate=12/31/2037
<...>
```

**Comment by Doout** [comment]
@xfabre was there any deployment of db2 before on your cluster? If `v11.5.1.0` was deployed, it might have not clean up the semaphores it created — the easiest way to fix this will to reboot the systems.

**Comment by xfabre** [comment]
@Doout Yep, I'm in a situation where there is another db2 deployment with `v11.5.1.0` in another namespace on the same cluster.
If it's not a supported case, I'm fine, you can close the ticket.
Thanks.

**Comment by Doout** [comment]
@xfabre At the moment we don't support more than one deployment on the same node. Is this a single node openshift cluster? If it is not you can try to reboot the node that db2 11.5.1.0-CN1 was deployed on and check if it faces the same issue.

You can check what node db2 was deployed one with `oc get po -o wide`

**Comment by xfabre** [comment]
@Doout It's a multi-node cluster but never-mind I can pick up a new one to install db2 11.5.1.0-CN1.
Thanks for your explanations.
