### ISSUE TITLE
db2u-nodes throwing init error

### ISSUE THREAD

**Issue by yathendra** [IBM/Db2#18]
i ran the command to install the DB2
`./db2u-install --db-type db2oltp --namespace db2bundlenew --db-name MYDB --release-name db2u-release-1 --existing-pvc db2pvc`

I have existing pvc and pv mapped to NFS server . When i run the above command , i notice **db2u-nodes** are throwing init error .

`
NAME                                          READY     STATUS       RESTARTS   AGE
db2u-release-1-db2u-0                         0/1       Init:Error   4          1m
db2u-release-1-db2u-ldap-7476d477d8-5967k     1/1       Running      0          1m
db2u-release-1-db2u-nodes-cfg-job-9z55v       0/1       Init:Error   0          1m
db2u-release-1-db2u-nodes-cfg-job-d9mt4       0/1       Init:Error   0          1m
db2u-release-1-db2u-nodes-cfg-job-rrpxk       0/1       Init:Error   0          1m
db2u-release-1-db2u-nodes-cfg-job-s5zws       0/1       Init:Error   0          1m
db2u-release-1-db2u-restore-morph-job-kl5vc   0/1       Init:0/1     0          1m
db2u-release-1-db2u-sqllib-shared-job-v8q4x   0/1       Completed    0          1m
db2u-release-1-db2u-tools-dc4fc6f9-8b9f8      1/1       Running      0          1m
db2u-release-1-etcd-0                         1/1       Running      0          1m
db2u-release-1-etcd-1                         1/1       Running      0          1m
db2u-release-1-etcd-2                         1/1       Running      0          1m `

**Comment by yathendra** [comment]
Do let me know if any information is needed .

**Comment by irinadel** [comment]
Hi @yathendra Please provide more diagnostic information - such as describe of the error pods to start with

**Comment by yathendra** [comment]
Hey sorry for the late response @irinadel . It was cluster issue and able to solve that . 

I would like to know will this support db2 11.1 developer edition ??
 I see it s pointing to db2 11.5 CE . is it feasible with db2 11.1 Developer Edition .
