### ISSUE TITLE
consider renaming the repo

### ISSUE THREAD

**Issue by stevemar** [IBM/Db2#20]
Please consider a more appropriate name, like db2-charts, or something more descriptive. Calling this just "Db2" is 1. vague, and 2. can be construed as an open-source version of Db2.

Renaming the repo will not break any links, Github will automatically add redirects so requests to https://github.com/IBM/Db2 will go to the new location.

**Comment by cg8** [comment]
Thanks @stevemar for your comments. Our vision is to extend this further than a chart level deployment.
