### ISSUE TITLE
Does this helm chart works on OpenShift 3.11 on IBM Cloud?

### ISSUE THREAD

**Issue by aroute** [IBM/Db2#30]
Which storageclass I should be using when deploying on IBM Cloud's OpenShift 3.11? Tried `ibmc-file-bronze` and `ibmc-block-bronze`. The block storage is getting error: `StorageClass "ibmc-block-bronze": "ReadWriteMany" is an unsupported access mode. Block Storage supports only 'ReadWriteOnce' mode`. The file storage also has issues out of the box.

**Comment by Doout** [comment]
It should be `ibm-file-gold` Please make sure to enable `no_root_squash` https://cloud.ibm.com/docs/FileStorage?topic=FileStorage-mountingLinux

This can be done using a daemonset as well https://github.com/IBM-Cloud/kube-samples/tree/master/daemonset-sample

**Comment by aroute** [comment]
Thanks. Documentation is really lacking. What IP do I use with the nodePort?

Was able to deploy using the `default` storageclass after applying the no_root-squash fix.

**Comment by Doout** [comment]
Any of the VM IP should work.

**Comment by vgovindan** [comment]
> Thanks. Documentation is really lacking. What IP do I use with the nodePort?
> 
> Was able to deploy using the `default` storageclass after applying the no_root-squash fix.

Did you use yaml to enable no_root-squash fix and restart worker nodes? Is there any specific reason for not using 'ibmc-file-gold'?

**Comment by aroute** [comment]
I switched to file-gold. Was able to deploy. However, I am not able to connect to the database from outside (using DBVisualizer and Data Studio). Used worker node IP, tried the Route as well. I can ping successfully but getting this error. Any ideas?

```
An error occurred while establishing the connection:

Details:
   Type: com.ibm.db2.jcc.am.SqlNonTransientConnectionException
   Error Code: -1639
   SQL State: 08001
```

**Comment by vgovindan** [comment]
I was able to deploy the image by binding the service account db2u to privileged SCC and without enabling  no_root-squash. However I faced the same issue  Error Code: -1639 while trying to connect from outside. On further research I found answers here https://www.ibm.com/support/pages/database-connection-fails-authentication-error-sql1639n.

For this the owner has to be changed for files db2chpw and db2ckpw from nobody to root. I was not able to do it as I haven't enabled  no_root-squash. I hope you will be able to do it as you have enabled no_root-squash.

**Comment by aroute** [comment]
Following the above document, I did the `chown root:root db2c`* on both files. Files changed permission from nobody:db2iadm1 to nobody:nobody. I then ran `/opt/ibm/db2/V11.5.0.0/instance/./db2iupdt -u db2fenc1 db2inst1`.

This did not help. Any suggestion?

**Comment by aroute** [comment]
This can be closed. I moved on to OCP 4.x. I was not able to deploy this helm chart; however, I was able to crop together a statefulset for Db2.
