### ISSUE TITLE
Support for Operators and Openshift 4.x

### ISSUE THREAD

**Issue by mikehenry-us** [IBM/Db2#7]
Hi!

Great start releasing Helm-charts for Db2U on OpenShift 3.x. Very exciting indeed!

As Tiller requires higher privileges and since we are running OpenShift 4, we would like to see a K8s Operator for Db2U so that we can also handle the full life-cycle of any Db2U-containers running.

Thank you in advance, and good luck going forward!

Cheers,

_-Mike_

**Comment by cg8** [comment]
@mikehenry-se 

Hi Mike, this is in our medium term roadmap (3 to 6 months out). Thank you for your feedback

~Loic

**Comment by mikehenry-us** [comment]
Sounds great! Looking forward to trying it out when you are ready.

_-Mike_

**Comment by cg8** [comment]
Closing this issue as this is in our short-term roadmap already.
